name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
    
    - name: Build and Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/v}
        
        # Update version in pom.xml
        mvn versions:set -DnewVersion=$VERSION
        
        # Build and deploy to GitHub Packages
        mvn -B clean deploy \
          -DskipTests \
          -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/Ldsystem/ekuiper4j
        
        # Create GitHub Release
        gh release create "v$VERSION" \
          --title "Release v$VERSION" \
          --generate-notes \
          --target main 